name: C build & Tests

on: [push, pull_request]


defaults:
	run:
		working-directory: section-01/circular-buffer-lib


jobs:
	build:
		strategy:
			matrix:
				os: [ubuntu-latest, macos-latest, windows-latest]
		runs-on: ${{ matrix.os }}

		steps:
			- name: Checkout
			  uses: actions/checkout@v4

			- name: Set up MSYS2 (Windows only)
			  if: runner.os == 'Windows'
			  uses: msys2/setup-msys2@v2
			  with:	
				msystem: MINGW64
				update: true
				install: >-
					mingw-w64-x86_64-gcc
					make
			
			- name: Build
			- run: make
			- shelll: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}

      			- name: Run unit tests
        		  run: make test
        		  shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
