name: Circular Buffer CI

on:
  push:
    branches: [ "**" ]
    paths:
      - "section-01/circular-buffer-lib/**"
      - ".github/workflows/circular-buffer-ci.yml"
  pull_request:
    branches: [ "**" ]
    paths:
      - "section-01/circular-buffer-lib/**"
      - ".github/workflows/circular-buffer-ci.yml"

# All steps run from the project folder
defaults:
  run:
    working-directory: section-01/circular-buffer-lib

jobs:
  linux-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build
        run: |
          set -e
          make clean || true
          make -j

      - name: Run tests (if present)
        run: |
          set -e
          if grep -qE '^\s*test\s*:' Makefile; then
            echo "Found 'test' target → running tests"
            make test
          elif grep -qE '^\s*run\s*:' Makefile; then
            echo "Found 'run' target → running"
            make run
          else
            echo "No 'test' or 'run' target in Makefile — skipping."
          fi

